name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Sync project deps (with tests + lint)
        run: uv sync --extra test --extra lint --frozen

      - name: Ruff format check
        run: uv run ruff format --check

      - name: Ruff lint
        run: uv run ruff check --output-format=github

      - name: Mypy type check
        run: uv run mypy src

      - name: Run tests
        env:
          GOOGLE_API_KEY: DUMMY
        run: uv run -m pytest -q -n auto
